### ISSUE TITLE
unable to load external .ply model

### ISSUE THREAD

**Issue by irudolf16** [JohnCoene/aframer#1]
Hi John 
I have the following issue: when I try to import a custom .ply model, the html inspector returns an error regarding the path of the model. I tried a lot of different pathway options without any success:

```r
library(aframer)
library(aextras)

shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
      embed_aframe(
        a_scene(
          a_dependency(),
          aextras_dependency(),
          a_assets(
            a_primitive(
              "asset-item",
              list(
                id = "model",
                src = "model.ply"
              )
            )
          ),
          a_sky(color = "#ECECEC"),
          a_entity(
            `ply-model` = "src: #model",
            rotation = "-90 0 0"
          )
        )
      )
    ),
title = "Dashboard example"
  ),
server = function(input, output) { }
)

``` 
Unfortunately, github does not support .ply files so I cannot upload the model, but I used one of those example models: https://people.sc.fsu.edu/~jburkardt/data/ply/airplane.ply

Thanks in advance for your help!

Cheers,

Isabelle Rudolf

**Comment by JohnCoene** [comment]
Hi Isabelle,

The reason this does not work is because Shiny does not server files in the root directory publicly and your `model.ply` should be, you need to place your model in a `www` directory, the rest of the code remains.

I created a small example [here](https://github.com/JohnCoene/shiny-aframer) using your model, look at the repository structure:

```r
library(shiny)
library(aframer)
library(aextras)

ui <- fluidPage(
  title = "aframer",
  fluidRow(
    column(
      12,
      embed_aframe(
        a_scene(
          height = "100vh",
          a_dependency(),
          aextras_dependency(),
          a_assets(
            timeout = "25000",
            a_primitive(
              "asset-item",
              list(
                id = "model",
                src = "model.ply"
              )
            )
          ),
          a_sky(color = "#ECECEC"),
          a_entity(
            `ply-model` = "src: #model",
            rotation = "-90 0 0"
          )
        )
      )
    )
  )
)

server <- function(input, output){}

shinyApp(ui, server)
```

One more thing you may have noticed above,  I set `timeout = 25000` in `a_assets` to increase the timeout llimit, this defaults to `3000` which might be short for large models that take time to load.

Let me know if this does not work, feel free to close if that answers your question. (I'll work on the doc and examples of `framer` later this year)

**Comment by DivadNojnarg** [comment]
Hi John,
The model is already in a www folder. Each time the html inspector returns an error saying that he cannot find model.ply ... Quite strange

**Comment by JohnCoene** [comment]
Have you tried cloning and running the example repo I linked to? I used your model and it worked fine. Could you send the exact error you see so that I look into it in more depth?

**Comment by irudolf16** [comment]
I cloned your example repo and now it works fine, thank you so much!

**Comment by DivadNojnarg** [comment]
@JohnCoene:
is there a limit in the model size? We tried with very complex ply models (detailed human body) and nothing can be displayed but no warning in the console.
Maybe there is an option to control that.

**Comment by JohnCoene** [comment]
No to my knowledge though [there is a section on it on the official website](https://aframe.io/docs/0.8.0/introduction/models.html#model-performance) I also believe that it depends on the model files you use `.ply` are larger than those split into `.obj` and `.mtl`.

EDIT: You may also want to see about the [hosting](https://aframe.io/docs/0.8.0/introduction/hosting-and-publishing.html#hosting-models)

**Comment by JohnCoene** [comment]
Did you find a solution?

**Comment by DivadNojnarg** [comment]
To be honest, this looks promising with ply models (I needed to rescale the original file):

```r
library(shiny)
library(aframer)
library(aextras)
library(htmltools)
library(magrittr)

# ctrl + alt + i -> visual inspector

model <- a_entity(
  `ply-model` = "src: #model",
  rotation = "-90 0 0"
) %>%
  tagAppendAttributes(scale = "0.01 0.01 0.01")

scene <- a_scene(
  a_dependency(),
  aextras_dependency(),
  a_assets(
    timeout = 25000,
    a_primitive(
      "asset-item",
      list(
        id = "model",
        src = "skull.ply"
      )
    )
  ),
  a_sky(color = "#ECECEC"),
  model
) #%>% 
  #tagAppendAttributes(stats = NA)


ui <- fluidPage(
  title = "aframer",
  fluidRow(
    column(
      12,
      embed_aframe(
        height = "100vh",
        scene
      )
    )
  )
)

server <- function(input, output){}

shinyApp(ui, server)
```

![capture d ecran 2018-09-21 a 16 01 20 2](https://user-images.githubusercontent.com/18291543/45885783-a2a22400-bdb7-11e8-91ad-25cf0616790e.png)


But I still do not know how to deal with mtl and obj. I replaced the attribute `ply-model` by `obj-model`, changed "src" by "obj", as shown in the aframer website and I load the obj file. I do not have any alert but nothing is displayed in the aframe inspector (ctrl + alt + i).

**Comment by JohnCoene** [comment]
[docs here](https://aframe.io/docs/0.8.0/components/obj-model.html#sidebar)

Do you also source the mtl filed and reference it in the `obj-model` primitive? I have used obj & mtl files successfully in the past, mainly from Google Poly.

**Comment by DivadNojnarg** [comment]
Yes I did. I would take any working example to compare, if you have one.

**Comment by JohnCoene** [comment]
Sorry for the late response, just back from holiday. 

I've updated the repo used for a previous examples: [https://github.com/JohnCoene/shiny-aframer](https://github.com/JohnCoene/shiny-aframer). It uses a model downloaded on [sketchfab](https://sketchfab.com/models/b6c27799b1ac43dbae5e78015b812b58)

**Comment by DivadNojnarg** [comment]
ok cool! Thanks
